image: Visual Studio 2017
environment: 
  PACKAGE_VERSION: 1.0.4
  ASSEMBLY_VERSION: $(PACKAGE_VERSION).$(APPVEYOR_BUILD_NUMBER)
version: $(PACKAGE_VERSION).$(APPVEYOR_BUILD_NUMBER)
build_script:
- cmd: dotnet restore
- cmd: dotnet msbuild -p:Configuration=Release -p:PackageVersion=%PACKAGE_VERSION% -p:AssemblyVersion=%ASSEMBLY_VERSION%
test:
  assemblies:
    - '**\*Tests.dll'
artifacts:
- path: nugets\*.nupkg