image: Visual Studio 2019
environment: 
  PACKAGE_VERSION: 1.0.13
  ASSEMBLY_VERSION: $(PACKAGE_VERSION).$(APPVEYOR_BUILD_NUMBER)
build_script:
- cmd: dotnet restore
- cmd: >
    dotnet msbuild 
    "-t:DeepCopy_Fody;DeepCopy;SmokeTest;AssemblyToProcess;Tests"
    -p:Configuration=Release
    -p:PackageVersion=%PACKAGE_VERSION%
    -p:AssemblyVersion=%ASSEMBLY_VERSION%
test:
  assemblies:
    - 'Tests\bin\Release\net472\Tests.dll'
    - 'Tests\bin\Release\netcoreapp2.2\Tests.dll'
artifacts:
- path: nugets\*.nupkg