image: Visual Studio 2017
version: '1.0.4.{build}'
build_script:
- cmd: dotnet restore
- cmd: dotnet msbuild -p:Configuration=Release
test:
  assemblies:
    - '**\*Tests.dll'
artifacts:
- path: nugets\*.nupkg