image: Visual Studio 2017
build_script:
- cmd: dotnet restore
- cmd: dotnet msbuild -p:Configuration=Release -p:PackageVersion=$(appveyor_build_version) -p:AssemblyVersion=$(appveyor_build_version)
test:
  assemblies:
    - '**\*Tests.dll'
artifacts:
- path: nugets\*.nupkg